### ISSUE TITLE
quadrone: Container Sheet - Keeping the footer in view when there's whitespace in the contents tab

### ISSUE THREAD

**Issue by kgar** [kgar/foundry-vtt-tidy-5e-sheets#1096]
When the container contents tab is generally empty, the sheet-wide scroll and the empty container contents table wrapper push the footer out of view, triggering the off-screen styles / sticky footer setup.

Ideally, we would like for the footer to be visible at the bottom of the visible area when there is ample room for it, instead of the flex settings on the item tables wrapper pushing it offscreen.

This can be accomplished with `grid-template-rows` setting `auto` being placed on the item tables wrapper, which will push the footer to the bottom of the viewing area and not the scroll container. 🎉

From the community (thanks CRASH!):
https://discord.com/channels/1167985253072257115/1260456739770466335/1356807245320687667

---

```scss
    .contents-footer.off-screen {
      // position: sticky;
      // bottom: 0;
      // transform: translateY(calc(100% - var(--t5e-size-6x)));

      // .meter.progress {
      //   border-bottom: 0;
      //   border-bottom-right-radius: 0;
      //   border-bottom-left-radius: 0;
      // }

      // // .meter.progress .label {
      // //   visibility: hidden;
      // // }

      // .item-create {
      //   display: none;
      // }
    }

  // ...

  .tidy-tab {
    // ...

    &.contents {
      display: grid;
      grid-template-rows: min-content auto min-content min-content min-content;
    }
  }

  // ...
  &.container {
    .contents-footer {
      display: flex;
      flex-direction: row;
      align-items: center;
      gap: var(--t5e-size-1x);
      position: sticky; // 👈
      bottom: 0; // 👈
    }
  }
```

https://github.com/kgar/foundry-vtt-tidy-5e-sheets/tree/prototype-keeping-container-footer-visible
