### ISSUE TITLE
bug: Make editor-based read-only description texts selectable for copy/paste

### ISSUE THREAD

**Issue by kgar** [kgar/foundry-vtt-tidy-5e-sheets#745]
Foundry, as a rule, sets `user-select: none` for all elements, for good reason.
This rule is overridden by prose mirror as `user-select: text` so that editor-based content can be selected / copied / pasted elsewhere.
Because of Tidy's current implementation of Prose Mirror readonly text, there are cases when it's not using the editor to show the markup. In these cases, select/copy/paste is not possible.

Create a helper class that can be put on any element to set it to `user-select: text`.
Identify all locations where Tidy uses prose mirror and ensure that the readonly content is selectable.

Sample css from Foundry:
```css
.editor-content * {
  -webkit-user-select: text;
  -moz-user-select: text;
  -ms-user-select: text;
  user-select: text;
}
```

Proposed Tidy class:
```css
.user-select-text * {
  -webkit-user-select: text;
  -moz-user-select: text;
  -ms-user-select: text;
  user-select: text;
}
```
