### ISSUE TITLE
bug: Incorrect path to foundry's public fonts

### ISSUE THREAD

**Issue by ssg3Davins** [kgar/foundry-vtt-tidy-5e-sheets#857]
In src/scss/core.scss the path should be one less ``` ../ ```,like everywhere else, otherwise it won't work with routeprefixes.
Current code:
```scss
@font-face {
  font-family: 'Signika';
  src: url('../../../fonts/signika/signika-light.woff2') format('woff2');
  font-weight: 300;
  font-style: normal;
}

@font-face {
  font-family: 'Signika';
  src: url('../../../fonts/signika/signika-semibold.woff2') format('woff2');
  font-weight: 500;
  font-style: normal;
}
```
